### ISSUE TITLE
Bluetooth verbindet sich schlecht

### ISSUE THREAD

**Issue by micw** [micw/skoda-enyaq-bugs#3]
Normalerweise verbindet sich ein Telefon via Bluetooth unmittelbar nach Einschalten des Fahrzeugs (funktioniert sonst bei allen Fahrzeugen, zu denen ich Zugriff habe). Beim Enyaq kommt die Verbindung manchmal erst nach etlichen Minuten zustande, manchmal auch gar nicht - dann muss die Verbindung manuell vom Telefon aus initiiert werden.

**Comment by lukee7** [comment]
Funktioniert mit einem Xiaomi Mi A3 und einem Mi Poco M3 zu 100%. Beide Handys immer und täglich bereits verbunden, bevor man das [lästige] OK bestätigt hat. Die Handys sind dabei in der [Hosen]tasche im Standbybetrieb.

**Comment by hghildeb** [comment]
Das könnte evtl. durch eine Energiespar-Einstellung am Handy verursacht werden

**Comment by micw** [comment]
Da ich mein altes Handy nicht mehr habe und das Verhalten mit keinem anderen Handy reproduzieren konnte, schließe ich das als nicht reproduzierbar.
